# Generated by Django 4.2.7 on 2025-11-29 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View')], help_text='Type of action performed', max_length=20)),
                ('resource_type', models.CharField(help_text='Type of resource (model name)', max_length=100)),
                ('resource_id', models.CharField(help_text='ID of the affected resource', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('success', models.BooleanField(default=True, help_text='Whether the action succeeded')),
                ('admin_user', models.ForeignKey(help_text='Admin user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_logs_created_43fcd6_idx'), models.Index(fields=['admin_user', '-created_at'], name='audit_logs_admin_u_49b499_idx'), models.Index(fields=['resource_type', '-created_at'], name='audit_logs_resourc_066d36_idx')],
            },
        ),
    ]
