# Generated by Django 4.2.7 on 2025-11-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('confirmation_code', models.CharField(db_index=True, help_text='Non-identifying confirmation code', max_length=20, unique=True)),
                ('incident_type', models.CharField(choices=[('harassment', 'Harassment'), ('stalking', 'Stalking'), ('impersonation', 'Impersonation'), ('threats', 'Threats'), ('other', 'Other')], db_index=True, help_text='Type of incident', max_length=20)),
                ('description', models.TextField(help_text='Encrypted incident description')),
                ('timestamp', models.DateTimeField(help_text='When the incident occurred')),
                ('location_free_text', models.CharField(blank=True, help_text='Platform/context (not physical location)', max_length=200)),
                ('evidence_links', models.JSONField(blank=True, default=list, help_text='URLs to evidence (no file uploads)')),
                ('consent_for_followup', models.BooleanField(default=False, help_text='Whether user consents to followup')),
                ('redaction_applied', models.BooleanField(default=False, help_text='Whether PII redaction was applied')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['incident_type', '-created_at'], name='reports_inciden_0b15b9_idx'), models.Index(fields=['confirmation_code'], name='reports_confirm_f3e6ad_idx')],
            },
        ),
    ]
