# Generated by Django 4.2.7 on 2025-11-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('title', models.CharField(help_text='Resource title', max_length=300)),
                ('description', models.TextField(help_text='Brief resource description')),
                ('content', models.TextField(help_text='Full resource content')),
                ('category', models.CharField(choices=[('legal_rights', 'Legal Rights'), ('safety_planning', 'Safety Planning'), ('organizations', 'Support Organizations'), ('laws', 'Laws & Legislation'), ('financial', 'Financial Assistance'), ('healthcare', 'Healthcare Resources')], db_index=True, help_text='Resource category', max_length=20)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('guide', 'Guide'), ('directory', 'Directory'), ('law', 'Law/Legislation'), ('organization', 'Organization')], db_index=True, help_text='Type of resource', max_length=20)),
                ('external_url', models.URLField(blank=True, help_text='Optional external link')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Whether resource is published')),
                ('tags', models.JSONField(default=list, help_text='Searchable tags')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'db_table': 'resources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_published'], name='resources_categor_e347af_idx'), models.Index(fields=['resource_type', 'is_published'], name='resources_resourc_1b6e23_idx')],
            },
        ),
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('name', models.CharField(help_text='Helpline name', max_length=200)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=50)),
                ('description', models.TextField(help_text='Helpline description')),
                ('category', models.CharField(choices=[('crisis', 'Crisis Support'), ('legal', 'Legal Assistance'), ('counseling', 'Counseling'), ('shelter', 'Shelter/Housing'), ('medical', 'Medical Services'), ('other', 'Other Support')], db_index=True, help_text='Helpline category', max_length=20)),
                ('availability', models.CharField(help_text="Availability hours (e.g., '24/7', 'Mon-Fri 9am-5pm')", max_length=200)),
                ('is_24_7', models.BooleanField(db_index=True, default=False, help_text='Whether available 24/7')),
                ('languages', models.JSONField(default=list, help_text='Supported languages')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether helpline is currently active')),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Display priority (higher = shown first)')),
            ],
            options={
                'verbose_name': 'Helpline',
                'verbose_name_plural': 'Helplines',
                'db_table': 'helplines',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['-priority', 'name'], name='helplines_priorit_98c6cf_idx'), models.Index(fields=['category', 'is_active'], name='helplines_categor_87191c_idx'), models.Index(fields=['is_24_7', 'is_active'], name='helplines_is_24_7_c44db6_idx')],
            },
        ),
    ]
