# Generated by Django 4.2.7 on 2025-11-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('title', models.CharField(help_text='Lesson title', max_length=200)),
                ('description', models.TextField(help_text='Brief lesson description')),
                ('category', models.CharField(choices=[('privacy', 'Privacy'), ('safety', 'Safety'), ('security', 'Security'), ('awareness', 'Awareness')], db_index=True, help_text='Lesson category', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Estimated completion time in minutes')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, help_text='Difficulty level', max_length=20)),
                ('content', models.JSONField(help_text='Structured lesson content')),
                ('quiz', models.JSONField(blank=True, default=list, help_text='Quiz questions and answers')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Lesson thumbnail image URL')),
                ('published', models.BooleanField(db_index=True, default=False, help_text='Whether lesson is published')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': 'lessons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'published'], name='lessons_categor_c04b06_idx'), models.Index(fields=['difficulty', 'published'], name='lessons_difficu_41d650_idx')],
            },
        ),
    ]
