# Generated by Django 4.2.7 on 2025-11-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('donor_email', models.EmailField(blank=True, help_text='Optional donor email for receipt', max_length=254)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Whether donation is anonymous')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Donation status', max_length=20)),
                ('payment_intent_id', models.CharField(help_text='Payment processor reference', max_length=255, unique=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from donor')),
                ('confirmation_code', models.CharField(db_index=True, help_text='Non-identifying confirmation code', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='donations_status_80555b_idx'), models.Index(fields=['confirmation_code'], name='donations_confirm_53974b_idx'), models.Index(fields=['payment_intent_id'], name='donations_payment_43c750_idx')],
            },
        ),
    ]
